env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
rules:
  camelcase: error
  class-methods-use-this: error
  no-console: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-unused-vars: 0
  no-shadow: 0
  valid-typeof:
    - error
    - requireStringLiterals: false
  import/extensions: 0
  import/prefer-default-export: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  "@typescript-eslint/array-type": error
  "@typescript-eslint/no-explicit-any": error
